import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Sparkles, Download, Copy } from 'lucide-react';
import { useTheme } from '../context/ThemeContext';

const AIReportModal = ({ isOpen, onClose, report, isLoading }) => {
  const { isDarkMode } = useTheme();

  if (!isOpen) return null;

  const formatInlineStyles = (text) => {
    // Handle bold (**text**)
    let parts = text.split(/(\*\*.*?\*\*)/g);
    return parts.map((part, i) => {
      if (part.startsWith('**') && part.endsWith('**')) {
        return <strong key={i} className="font-bold text-gray-900 dark:text-white">{part.slice(2, -2)}</strong>;
      }
      // Handle italic (*text* or _text_)
      // Note: This is a simple implementation and might not handle nested styles perfectly
      return part.split(/(\*.*?\*|_.*?_)/g).map((subPart, j) => {
         if ((subPart.startsWith('*') && subPart.endsWith('*')) || (subPart.startsWith('_') && subPart.endsWith('_'))) {
            return <em key={`${i}-${j}`} className="italic text-gray-700 dark:text-gray-200">{subPart.slice(1, -1)}</em>;
         }
         return subPart;
      });
    });
  };

  const renderContent = (text) => {
    if (!text) return null;
    
    return text.split('\n').map((line, index) => {
      // Headers
      if (line.startsWith('# ')) {
        return <h1 key={index} className="text-2xl font-bold mb-4 mt-6 text-indigo-600 dark:text-indigo-400">{line.replace('# ', '')}</h1>;
      }
      if (line.startsWith('## ')) {
        return <h2 key={index} className="text-xl font-bold mb-3 mt-5 text-gray-800 dark:text-gray-100">{line.replace('## ', '')}</h2>;
      }
      if (line.startsWith('### ')) {
        return <h3 key={index} className="text-lg font-bold mb-2 mt-4 text-gray-700 dark:text-gray-200">{line.replace('### ', '')}</h3>;
      }
      
      // List items (handle both - and *)
      if (line.trim().startsWith('- ') || line.trim().startsWith('* ')) {
        const content = line.trim().substring(2);
        return (
          <div key={index} className="flex items-start gap-2 mb-2 ml-4">
            <span className="mt-2 w-1.5 h-1.5 rounded-full bg-indigo-500 flex-shrink-0" />
            <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
              {formatInlineStyles(content)}
            </p>
          </div>
        );
      }

      // Numbered lists (1. )
      if (/^\d+\.\s/.test(line)) {
         return (
          <div key={index} className="flex items-start gap-2 mb-2 ml-4">
            <span className="font-bold text-indigo-500 min-w-[20px]">{line.match(/^\d+\./)[0]}</span>
            <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
              {formatInlineStyles(line.replace(/^\d+\.\s/, ''))}
            </p>
          </div>
        );
      }

      // Empty lines
      if (!line.trim()) {
        return <div key={index} className="h-2" />;
      }

      // Regular paragraphs
      return (
        <p key={index} className="mb-2 text-gray-600 dark:text-gray-300 leading-relaxed">
          {formatInlineStyles(line)}
        </p>
      );
    });
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(report);
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.95 }}
            className={`relative w-full max-w-3xl max-h-[85vh] overflow-hidden rounded-2xl shadow-2xl ${
              isDarkMode ? 'bg-gray-900 text-white' : 'bg-white text-gray-900'
            }`}
          >
            {/* Header */}
            <div className={`flex items-center justify-between p-6 border-b ${
              isDarkMode ? 'border-gray-800' : 'border-gray-100'
            }`}>
              <div className="flex items-center gap-3">
                <div className={`p-2 rounded-lg ${
                  isDarkMode ? 'bg-indigo-500/20 text-indigo-400' : 'bg-indigo-50 text-indigo-600'
                }`}>
                  <Sparkles size={24} />
                </div>
                <div>
                  <h2 className="text-xl font-bold">AI Performance Report</h2>
                  <p className={`text-sm ${isDarkMode ? 'text-gray-400' : 'text-gray-500'}`}>
                    Generated by AI Analyst
                  </p>
                </div>
              </div>
              <button
                onClick={onClose}
                className={`p-2 rounded-full transition-colors ${
                  isDarkMode ? 'hover:bg-gray-800 text-gray-400' : 'hover:bg-gray-100 text-gray-500'
                }`}
              >
                <X size={20} />
              </button>
            </div>

            {/* Content */}
            <div className="p-6 overflow-y-auto max-h-[60vh]">
              {isLoading ? (
                <div className="flex flex-col items-center justify-center py-12 space-y-4">
                  <div className="relative w-16 h-16">
                    <div className="absolute inset-0 border-4 border-indigo-200 rounded-full animate-pulse"></div>
                    <div className="absolute inset-0 border-t-4 border-indigo-600 rounded-full animate-spin"></div>
                  </div>
                  <p className={`text-lg font-medium ${isDarkMode ? 'text-gray-300' : 'text-gray-600'}`}>
                    Analyzing your performance...
                  </p>
                  <p className={`text-sm ${isDarkMode ? 'text-gray-500' : 'text-gray-400'}`}>
                    Crunching numbers and generating insights
                  </p>
                </div>
              ) : (
                <div className={`prose max-w-none ${isDarkMode ? 'prose-invert' : ''}`}>
                  <div className="font-sans text-base">
                    {renderContent(report)}
                  </div>
                </div>
              )}
            </div>

            {/* Footer */}
            {!isLoading && (
              <div className={`flex items-center justify-end gap-3 p-6 border-t ${
                isDarkMode ? 'border-gray-800' : 'border-gray-100'
              }`}>
                <button
                  onClick={handleCopy}
                  className={`flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-lg transition-colors ${
                    isDarkMode 
                      ? 'bg-gray-800 hover:bg-gray-700 text-gray-300' 
                      : 'bg-gray-100 hover:bg-gray-200 text-gray-700'
                  }`}
                >
                  <Copy size={16} />
                  Copy Report
                </button>
                <button
                  onClick={onClose}
                  className="px-4 py-2 text-sm font-medium text-white bg-indigo-600 rounded-lg hover:bg-indigo-700 transition-colors"
                >
                  Done
                </button>
              </div>
            )}
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
};

export default AIReportModal;
